// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dfqimfiymhigmlzwckcv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRmcWltZml5bWhpZ21sendja2N2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MTUwMDIsImV4cCI6MjA2NDQ5MTAwMn0.e2KJLnshPZcuKQ3F213Wn3u314jXQZHTwoB10MnCa7I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);